on:
  push:
    paths:
      - 'data/**'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.UBERSHMEKEL_ALT_TOKEN }}
      # install node 14.x
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: 'Run Script'
        run: 'node run script.js'
      - name: 'commit files'
        run: '|
          git config --local user.email "$(git log -n 1 --pretty=format:%an)"
          git config --local user.name "$(git log -n 1 --pretty=format:%ae)"
          git add --all
          git commit -am "add data"
          git push'