name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Actions CI
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Setup Go binary path
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}"
        echo "::add-path::${{ github.workspace }}/bin"

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/estesp/actions-playground
        fetch-depth: 25

    - name: r00t Build
      working-directory: src/github.com/estesp/actions-playground
      run: |
        echo "ACTIONS ENV:"
        env
        sudo make binary
        sudo ./install-runc

    - name: Build
      working-directory: src/github.com/estesp/actions-playground
      run: |
        make binary
