on:
  push:
  # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
  name: Containerd Release
  
  jobs:
    build:
      name: Build Release Binaries
      runs-on: ${{ matrix.os }}
      timeout-minutes: 10
  
      strategy:
        matrix:
          os: [ubuntu-18.04, windows-2019]

      steps:
        - name: Install Go
          uses: actions/setup-go@v1
          with:
            go-version: '1.13.11'

        - name: Set env
          shell: bash
          run: |
            echo "::set-env name=GOPATH::${{ github.workspace }}"
            echo "::add-path::${{ github.workspace }}/bin"

        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: containerd/containerd
            path: src/github.com/containerd/containerd

        - name: Install Linux dependencies
            if: startsWith(matrix.os, 'ubuntu')
            run: |
              sudo apt-get install -y btrfs-tools libseccomp-dev
    
        - name: Make
            run: |
              make build
              make binaries
            working-directory: src/github.com/containerd/containerd

    release:
        name: Create Release
        runs-on: ubuntu-18.04
        timeout-minutes: 10
        needs: [build]

        steps:
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false